name: Generate Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Rust environment
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install git-cliff
        run: cargo install git-cliff

      - name: Generate Changelog
        run: git cliff -c cliff.toml > CHANGELOG.md

      - name: Commit and Push Changelog
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
